name: FixBot
on:
  workflow_dispatch:
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  FixBot:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    needs: []
    strategy:
      fail-fast: false
      matrix: # hello world
        version:
          - '1.10.6'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
          - x86
        exclude:
          - os: ubuntu-latest
            arch: x86
          - os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WILLOW_BOT_TOKEN }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Set and Retrieve Github ENV variables
        shell: bash
        run: |
          echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run tests
        run: |
          julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
          julia --color=yes test/runtests.jl --overwrite

      - name: Commit changes
        run: |
          git config --global user.email "willow-bot@users.noreply.github.com"
          git config --global user.name "Willow Bot"
          git config pull.rebase false  # merge
          git add docs/src/*
          git add test/reference*/*
          git status
          git diff
          git diff-index --quiet HEAD || git commit -m "Regenerate test output"
          git pull
          git push
